//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AST_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AST_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.AST_Config", typeof(AST_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not use {0} in the Opener..
        /// </summary>
        internal static string DoesNotUseEarthlyStarInTheOpener {
            get {
                return ResourceManager.GetString("DoesNotUseEarthlyStarInTheOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency {0} Priority:.
        /// </summary>
        internal static string Emergency0Priority {
            get {
                return ResourceManager.GetString("Emergency0Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follows normal targeting plan.
        /// </summary>
        internal static string FollowsNormalTargetingPlan {
            get {
                return ResourceManager.GetString("FollowsNormalTargetingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite Non-DPS Cards.
        /// </summary>
        internal static string OverwriteNonDPSCards {
            get {
                return ResourceManager.GetString("OverwriteNonDPSCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places at own feet only.
        /// </summary>
        internal static string PlacesAtOwnFeetOnly {
            get {
                return ResourceManager.GetString("PlacesAtOwnFeetOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Places {0} in the Opener..
        /// </summary>
        internal static string PlacesEarthlyStarInTheOpener {
            get {
                return ResourceManager.GetString("PlacesEarthlyStarInTheOpener", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard {0} Priority: .
        /// </summary>
        internal static string Standard0Priority {
            get {
                return ResourceManager.GetString("Standard0Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use when Target is at or below HP% (0% = Never Detonate Early, 100% = Detonate ASAP)..
        /// </summary>
        internal static string UseWhenTargetIsAtOrBelowHP0NeverDetonateEarly100DetonateASAP {
            get {
                return ResourceManager.GetString("UseWhenTargetIsAtOrBelowHP0NeverDetonateEarly100DetonateASAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will draw even if you have healing cards remaining..
        /// </summary>
        internal static string WillDrawEvenIfYouHaveHealingCardsRemaining {
            get {
                return ResourceManager.GetString("WillDrawEvenIfYouHaveHealingCardsRemaining", resourceCulture);
            }
        }
    }
}
