//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WrathCombo.Resources.Localization.JobConfigs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BLM_Config {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BLM_Config() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WrathCombo.Resources.Localization.JobConfigs.BLM_Config", typeof(BLM_Config).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Blizzard I / III / IV in Umbral Ice depending on stacks and level.
        /// </summary>
        internal static string AddBlizzardOr3Or4DependingOnStackAndLevel {
            get {
                return ResourceManager.GetString("AddBlizzardOr3Or4DependingOnStackAndLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Despair when in Astral Fire and below 2400 MP..
        /// </summary>
        internal static string AddDespairWhenBelow2400MP {
            get {
                return ResourceManager.GetString("AddDespairWhenBelow2400MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Despair when in Astral Fire and above 800 MP..
        /// </summary>
        internal static string AddDespairWhenInAFAndAbove800MP {
            get {
                return ResourceManager.GetString("AddDespairWhenInAFAndAbove800MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Fire I / III when in Astral Fire and stack is less than 3.
        /// </summary>
        internal static string AddFireOrFire3WhenInAF {
            get {
                return ResourceManager.GetString("AddFireOrFire3WhenInAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Flarestar in Astral Fire when ready..
        /// </summary>
        internal static string AddFlarestarinAF {
            get {
                return ResourceManager.GetString("AddFlarestarinAF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not use while under the effect of Leylines.
        ///This is the recommended behaviour..
        /// </summary>
        internal static string DoNotUseUnderLeylines {
            get {
                return ResourceManager.GetString("DoNotUseUnderLeylines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaves Fire in Umbral Ice 
        ///Will Use Fire I / III if selected above..
        /// </summary>
        internal static string DontChangeFireInUmbralIce {
            get {
                return ResourceManager.GetString("DontChangeFireInUmbralIce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many charges to save for manual use?.
        /// </summary>
        internal static string HowManyChargesForManualUse {
            get {
                return ResourceManager.GetString("HowManyChargesForManualUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many charges to save for movement?.
        /// </summary>
        internal static string HowManyChargesForMovement {
            get {
                return ResourceManager.GetString("HowManyChargesForMovement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many charges of Triplecast to keep ready? (0 = Use all).
        /// </summary>
        internal static string HowManyChargesTriplecast {
            get {
                return ResourceManager.GetString("HowManyChargesTriplecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manaward HP percentage threshold.
        /// </summary>
        internal static string ManawardHPThreshold {
            get {
                return ResourceManager.GetString("ManawardHPThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not under Leylines.
        /// </summary>
        internal static string NotUnderLeylines {
            get {
                return ResourceManager.GetString("NotUnderLeylines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces Blizzard3 with Blizzard when in Umbral Ice III..
        /// </summary>
        internal static string ReplaceBlizzard3WithBlizzardWhenInUI3 {
            get {
                return ResourceManager.GetString("ReplaceBlizzard3WithBlizzardWhenInUI3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces Blizzard with Blizzard3 when out of Umbral Ice III..
        /// </summary>
        internal static string ReplaceBlizzardWithBlizzard3WhenNotInUI3 {
            get {
                return ResourceManager.GetString("ReplaceBlizzardWithBlizzard3WhenNotInUI3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces Fire3 with Fire when in Astral Fire III..
        /// </summary>
        internal static string ReplaceFire3WithFireWhenInAF3 {
            get {
                return ResourceManager.GetString("ReplaceFire3WithFireWhenInAF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces Fire with Fire3 when out of Astral Fire III or not in combat..
        /// </summary>
        internal static string ReplaceFireWithFire3WhenNotInAF3OrCombat {
            get {
                return ResourceManager.GetString("ReplaceFireWithFire3WhenNotInAF3OrCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes it so that Xenoglossy also shows when Amplifier is on cooldown..
        /// </summary>
        internal static string ShowXenoglossyWhenAmplifierIsOnCooldown {
            get {
                return ResourceManager.GetString("ShowXenoglossyWhenAmplifierIsOnCooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Xenoglossy when Amplifier is on cooldown.
        /// </summary>
        internal static string ShowXenoglossyWhenAmplifierOnCD {
            get {
                return ResourceManager.GetString("ShowXenoglossyWhenAmplifierOnCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Using Thunder2 When Target HP% is at or Below (Set to 0 to Disable This Check).
        /// </summary>
        internal static string StopUsingThunder2 {
            get {
                return ResourceManager.GetString("StopUsingThunder2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Despair when below 1500 MP and when it is an instant cast (lvl 100 only)..
        /// </summary>
        internal static string UseDespairWhenBelow1500MP {
            get {
                return ResourceManager.GetString("UseDespairWhenBelow1500MP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Fire III when you have firestarter proc..
        /// </summary>
        internal static string UseFire3WhenYouHaveFirestarterProc {
            get {
                return ResourceManager.GetString("UseFire3WhenYouHaveFirestarterProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Foul/Xenoglossy..
        /// </summary>
        internal static string UseFoulOrXenoglossy {
            get {
                return ResourceManager.GetString("UseFoulOrXenoglossy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Paradox when in AF 3..
        /// </summary>
        internal static string UseParadoxWhenInAF3 {
            get {
                return ResourceManager.GetString("UseParadoxWhenInAF3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Scathe..
        /// </summary>
        internal static string UseScathe {
            get {
                return ResourceManager.GetString("UseScathe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Swiftcast when you don&apos;t have Triplecast..
        /// </summary>
        internal static string UseSwiftcastWhenNoTriplecast {
            get {
                return ResourceManager.GetString("UseSwiftcastWhenNoTriplecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Triplecast when you don&apos;t have swiftcast active..
        /// </summary>
        internal static string UseTriplecastWhenNoSwiftcast {
            get {
                return ResourceManager.GetString("UseTriplecastWhenNoSwiftcast", resourceCulture);
            }
        }
    }
}
